def set_columns_report(tableWidgetreport):
    tableWidgetreport.setColumnWidth(0, 75)
    tableWidgetreport.setColumnWidth(1, 50)
    tableWidgetreport.setColumnWidth(2, 90)
    tableWidgetreport.setColumnWidth(3, 85)
    tableWidgetreport.setColumnWidth(4, 120)
    tableWidgetreport.setColumnWidth(5, 30)
    tableWidgetreport.setColumnWidth(6, 30)
    tableWidgetreport.setColumnWidth(7, 160)
    tableWidgetreport.setColumnWidth(8, 80)
    tableWidgetreport.setColumnWidth(9, 50)
    tableWidgetreport.setColumnWidth(10, 50)
    tableWidgetreport.setColumnWidth(11, 50)
    tableWidgetreport.setColumnWidth(12, 50)
    tableWidgetreport.setColumnWidth(13, 50)
    tableWidgetreport.setColumnWidth(14, 133)
    tableWidgetreport.setColumnWidth(15, 100)
    tableWidgetreport.setColumnWidth(16, 50)
    tableWidgetreport.setColumnWidth(17, 50)


